command:
- "python"
- "app.py"

resources:
  serving-endpoint:
    name: "mas-93856fe9-endpoint"
    permission: "CAN_QUERY"
  database:
    database_name: "komae_demo_v4"
    instance_name: "komae-pg"
    permission: "CAN_CONNECT_AND_CREATE"

env:
- name: "DATABRICKS_ENDPOINT_NAME"
  valueFrom: serving-endpoint